### ISSUE TITLE
HealthCheck rate limit error

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#106]
The AWS HealthCheck request sometimes results in a rate limit error when executed on a stream that does not have messages resulting in the following error.

`Rate exceeded for shard shardId-000000000001 in stream integrations-test-kinesis-stream under account 459220251735. (Service: Kinesis, Status Code: 400, Request ID: f6926cb6-c693-40d7-a318-b2b3c5821111)`

This is most likely due to tight looping when iterating through a shard.

Investigate how to avoid rate limiting errors with the AWS SDK. The solution might be retrying, adding a delay or exponential backoff between requests, or to adjust the shard iterator request parameters to include a larger block of time.

**Comment by ceruleancee** [comment]
Unable to reproduce issue. 
Tested multiple calls, added extra looping in the code, and used similar parameters. 
At this point there is nothing more that we can do until someone encounters this issue.
We will continue to look out for this issue, should it occur again.
