### ISSUE TITLE
Palo Alto Input parser does not properly capture quoted values

### ISSUE THREAD

**Issue by waynekearns** [Graylog2/graylog-plugin-integrations#15]
## Description
Palo Alto logs are comma separated with optional double quotes for values that may include a comma. In the case of a quoted value, the Palo Alto Input breaks and counts the comma within the quotes and shifts the fields.

## Steps To Reproduce

1.Forward Palo Alto logs to Palo Alto TCP Input for a Firewall with ThreatDetect enabled.
2. Send a log containing a comma in any field.
3. Observe as the fields shift.

A packet capture containing the offending messages are included.

[palo.pcap.gz](https://github.com/Graylog2/graylog-plugin-integrations/files/3045602/palo.pcap.gz)

## Environment

- Graylog Version: 3.0
- Elasticsearch Version: 6.6
- MongoDB Version: 4.0.2
- Browser Version: All (tested 4 different browsers)

**Comment by danotorrey** [comment]
I am investigating this issue now.

**Comment by danotorrey** [comment]
The fix for this is to use an actual CSV parser to parse the PA payload instead of just straight splitting on commas.

This causes quoted CSV values with embedded commas to be parsed correctly as a single value. eg. "Testing 1, 2, 3" will now be correctly parsed as a single value.

A 3.0 snapshot build jar has been provided to @waynekearns. Thanks for testing @waynekearns!

**Comment by danotorrey** [comment]
@waynekearns mentioned that additional unhandled cases were found. Details will be provided shortly.

**Comment by waynekearns** [comment]
I don't yet have a PCAP.


[Palo_alto_Broken_messages-20190408.txt](https://github.com/Graylog2/graylog-plugin-integrations/files/3058907/Palo_alto_Broken_messages-20190408.txt)

**Comment by danotorrey** [comment]
Thank you @waynekearns! I will take a look and continue to investigate.

**Comment by danotorrey** [comment]
Thank you @waynekearns! I will take a look and continue to investigate. 

Can you tell me anything more about the specific issue/s that are happening now? (eg. malformed parsing, parsing errors)?

**Comment by danotorrey** [comment]
My testing with the latest PCAP shows that this issue is resolved with the latest snapshot build. @waynekearns is going to test a new snapshot build at the customer site to confirm (probably tomorrow).
