### ISSUE TITLE
Implement API shell for auto-setup

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#165]
Implement the actual API calls for the auto-setup flow based on the flowcharting done in #164. 

This should include individual methods for each setup step, and an overall method for them all. The stretch goal, which we are really optimistic about meeting is using the individual steps, so the user interface can provide a nice progress status update when each step is underway. Eg. the user will know when each step if successful and will have an idea of how the setup is progressing. Since the setup can take up to a minute to complete, the improved UI that shows the progress will be very helpful.

This issue should only cover implementing the shell of the API resource endpoints, so that integration with the frontend can occur.

**Comment by ceruleancee** [comment]
```
1.  Create a new Kinesis stream and check that its active
    INPUT: credentials and streamName acquire from the user
    OUTPUT: String streamArn
    BACKEND DETAILS:
    void createKinesisStream(KinesisClient kinesisClient, String stream)
    StreamDescription streamDescription = checkKinesisStreamStatus(kinesisClient, stream);
    String streamArn = streamDescription.streamARN();


4.  Add role with required permissions and acquire roleArn
    INPUT: roleName acquired from the user
    OUTPUT: streamARN acquired from step 3
    BACKEND DETAILS:
    void setRolePermissions(iam, roleName, streamArn, region.toString());
    String roleArn = getNewRolePermissions(iam, roleName);

5.  Add the subscription to the Cloudwatch log group for kinesis
    INPUT: credentials, logGroup, filterName, filterPattern acquired from user
    OUTPUT: streamArn acquired from step 3
    BACKEND DETAILS:
    roleArn acquired from step 4
    void addSubscriptionFilter(String logGroup, CloudWatchLogsClient cloudWatch, String streamArn, String roleArn, String filterName, String filterPattern)
```
