### ISSUE TITLE
Region selection lost

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#185]
The region selection is lost when returning to the StepAuthorize page. To reproduce the issue, return to the StepAuthorize page from a subsequent page in the wizard.

**Comment by danotorrey** [comment]
The region selection is lost when returning to the StepAuthorize page. 

@kyleknighted I believe we were aware of this. Just creating an issue as a reminder for us to fix.

**Comment by kyleknighted** [comment]
Manually closing since #199 was merged
