### ISSUE TITLE
Support Interface VPC Endpoints for Kinesis Data Streams

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-integrations#271]
# Description

A common pattern to avoid Kinesis traffic leaving a VPC is to use VPC endpoints instead of the public endpoint URLs.

## What

Allow to specify a private VPC endpoint URL instead of always using the public Kinesis endpoint URL.

## Why

If a user has set up their environments to use VPC endpoints, they cannot use the Graylog AWS plugin with it, because we don't allow overriding the Kinesis URL.
Follow https://github.com/awsdocs/amazon-kinesis-data-streams-developer-guide/blob/master/doc_source/vpc.md#using-interface-vpc-endpoints-for-kinesis-data-streams for more details.

**Comment by danotorrey** [comment]
Clients that need support for Endpoints.
- CloudWatch
- DynamoDB
- IAM
- Kinesis

**Comment by bernd** [comment]
This has been fixed in https://github.com/Graylog2/graylog-plugin-integrations/pull/279
