### ISSUE TITLE
Only Palo Alto Networks Input available, no AWS Kinesis/CloudWatch Input

### ISSUE THREAD

**Issue by LeeU1911** [Graylog2/graylog-plugin-integrations#326]
## Description
After installing `graylog-integrations-plugins`, only Palo Alto Networks Input is available when we want to launch new Input, AWS Kinesis/Cloudwatch Input isn't available for some reason
## Steps To Reproduce
N/A

## Environment

- Graylog Version: 3.1.3
- Elasticsearch Version: 6.5.4
- MongoDB Version: 3
- Browser Version: Firefox 70.0.1

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
