### ISSUE TITLE
IPv6 flows are not properly added to message field

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-integrations#329]
Since IPFIX flows don't have a message field by themselves, we generate a description for them: https://github.com/Graylog2/graylog-plugin-ipfix/blob/initial-version/src/main/java/org/graylog/plugins/ipfix/codecs/IpfixCodec.java#L68-L86

The code currently only considers IPv4 flows, which causes IPv6 flows to show "null" in the message text.

If there are no IPv4 fields, fall back to using the v6 ones.

![image](https://user-images.githubusercontent.com/52014/66208056-8ddbba00-e6b4-11e9-92ed-7ba02a95ee3b.png)

**Comment by danotorrey** [comment]
@ceruleancee @lingpri I believe this issue was fixed with #309. Can it be closed?

https://github.com/Graylog2/graylog-plugin-integrations/blob/6c53151852e0332026d2075d9591fef52f18fccf/src/main/java/org/graylog/integrations/ipfix/codecs/IpfixCodec.java#L103-L126
