### ISSUE TITLE
Cloudwatch documentation link not working

### ISSUE THREAD

**Issue by ceruleancee** [Graylog2/graylog-plugin-integrations#345]
## Description

In the AWS Kinesis/Cloudwatch Input, in the Kinesis Setup step, the Cloudwatch Log Subscription link does not lead to the designated link, but instead leads to page not found.

![Screen Shot 2019-12-16 at 2 07 01 PM](https://user-images.githubusercontent.com/22039395/70940545-2de88480-2010-11ea-9027-3a5f3ba8d50d.png)
![Screen Shot 2019-12-16 at 2 27 05 PM](https://user-images.githubusercontent.com/22039395/70940549-30e37500-2010-11ea-91f6-bde9c58aee70.png)

**Comment by danotorrey** [comment]
The incorrect link is likely located in UI (`.jsx`) code. It should be possible to find and replace to specify the correct link.
