### ISSUE TITLE
Support structured data in IPFIX templates: subtemplatelist

### ISSUE THREAD

**Issue by ceruleancee** [Graylog2/graylog-plugin-integrations#347]
The IPFIX parser currently only supports the standard scalar fields but not the ones described in [RFC 6313](https://tools.ietf.org/html/rfc6313).

The structured fields should be flattened into message fields in Graylog, because we don't have good support for nested/repeated fields yet.

the example rfc 6313 gives probably helps a bit, too https://tools.ietf.org/html/rfc6313#section-9.3

Provide support for parsing [ subtemplatelist ](https://tools.ietf.org/html/rfc6313#section-4.5.2)

**Comment by lingpri** [comment]
closed by PR #378
