### ISSUE TITLE
Allow for Assume Role AWS Integration

### ISSUE THREAD

**Issue by estein9825** [Graylog2/graylog-plugin-integrations#367]
# Description
AWS Kinesis/Cloudwatch Setup requires providing the IAM User Access ID and Secret saved into graylog. Ideally it would be better to allow for the assumed role lookups offered by all other AWS CLI commands
## What
Offer AWS IAM Assumed Role ability for AWS Kinesis/Cloudwatch Setup
## Why
It's best practice to expire Access Keys on a regular basis, which will require going back into graylog and updating it.  Not only that, it's best not to store passwords anywhere if it can be helped.

**Comment by bernd** [comment]
@estein9825 Thank you for the report. Using assume role will be possible in the upcoming 3.1.4 release.
