### ISSUE TITLE
Refactor Forwarder License Check

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog-plugin-integrations#449]
As a Graylog Engineer, I want to refactor the Forwarder to use the Enterprise License Checker in order to keep all code consistent on the same license checker.

*Input Criteria*
- [ ] Enterprise License Checker exists

*Acceptance Criteria*
- [ ] Forwarder migrated to Enterprise License Checker
- [ ] Forwarder License Checker removed from codebase
- [ ] Forwarder functionality validated post-migration

**Comment by lingpri** [comment]
duplicate issue
https://github.com/Graylog2/graylog-plugin-enterprise-integrations/issues/157

**Comment by waab76** [comment]
Closing as duplicate of Graylog2/graylog-plugin-enterprise-integrations#157
