### ISSUE TITLE
Verify Pager Duty Support for 3.1

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog-plugin-integrations#527]
## Description

Current Docs say PagerDuty is able to run on 3.1, but from Field testing [HERE](https://twitter.com/fymd/status/1285838079404761088) It seems it is only working on 3.3.  New need to test on 3.1, and if it does not work, we need to bump the required version to 3.3 in the docs

## Steps To Reproduce

1. Create a Pager Duty Dev Account: https://developer.pagerduty.com/sign-up/
2. Install Current Pager Duty Plugin in 3.1 and Generate Alert as shown: https://github.com/graylog-labs/graylog-plugin-pagerduty
3. Verify Working on 3.1, and if not bump README.md to 3.3

## Environment

- Graylog Version: 3.1

**Comment by jalogisch** [comment]
just for reference: https://github.com/graylog-labs/graylog-plugin-pagerduty/issues/11

**Comment by jalogisch** [comment]
Just tested this:

- installed OVA 3.1.4
- installed the pagerduty plugin 2.0.0
- restarted Graylog - no plugin available

![image](https://user-images.githubusercontent.com/404238/88186711-dc534880-cc35-11ea-9acb-f094a1174e9e.png)

actually the readme needs to be adjusted or the plugin. 

It does work in 3.3.x

**Comment by cameronattard** [comment]
@jalogisch @florianpopp are there any plans to resolve this?

**Comment by waab76** [comment]
Documentation updated: https://github.com/graylog-labs/graylog-plugin-pagerduty/blob/master/README.md
