### ISSUE TITLE
Upgrade Alert Notification Type "HTTP Notification"

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog-plugin-integrations#734]
# Description
Customers have been asking for an update to the HTTP Notification adapter to add in more information to the post via Headers.  Users are wanting to include additional information in the POST to tools like Ticket Systems, SOAR where they can pass more enrichment to the other end.

## What
Adjust the HTTP Notification type to include the ability to add more data to the POST method.  If we could allow for body information and headers.

**Comment by bernd** [comment]
Related issues:

- https://github.com/Graylog2/graylog-plugin-enterprise/issues/1137
- https://github.com/Graylog2/graylog2-server/issues/2333
- https://github.com/Graylog2/graylog2-server/issues/4658
- https://github.com/Graylog2/graylog2-server/issues/6119
- https://github.com/Graylog2/graylog2-server/issues/9508

**Comment by paasi6666** [comment]
Any updates on this feature request?

**Comment by unbreakabl3** [comment]
The same question

**Comment by kingzacko1** [comment]
Closing this with Graylog2/graylog2-server#16758. New `Custom HTTP Notification` type supports customizing the HTTP headers, method (added `GET` and `PUT` options), and body for the existing JSON payload. Also adds `text/plain` and `application/x-www-form-urlencoded` content types. Feedback on the new notification type is welcome, thank you in advance.
