### ISSUE TITLE
Allow for authentication credentials to be specified in HTTP notification configuration

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog-plugin-integrations#769]
# Description
As an end user, I'd like to be able to add an API key to my HTTP notification configuration for an endpoint that requires authentication. 

## Why
This is in relation to HS-330903639.

**Comment by asachs01** [comment]
@bernd I think I opened this in the wrong repo--maybe it should be in the enterprise plugin repo?

**Comment by bernd** [comment]
@asachs01 The HTTP notification plugin is part of the open source core product. But I think we can leave it here for now. We can always move it to the server repo if needed.

**Comment by bernd** [comment]
Refs https://github.com/Graylog2/graylog2-server/issues/4658
