### ISSUE TITLE
graylog4 elasticsearch input

### ISSUE THREAD

**Issue by Soberabsurd** [Graylog2/graylog-plugin-integrations#809]
I want to use GrayLog4 Input to read ElasticSearch data, but I don't see any ElasticSearch input, and I don't find any plugin for ElasticSearch on the plugin page。How can I read ElasticSearch data directly?

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
