### ISSUE TITLE
Add permissions checking for AWS API calls

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog-plugin-integrations#88]
Add permissions checking for AWS API calls.

**Comment by danotorrey** [comment]
@danotorrey to take a look at notes to find out what we decided on this.

**Comment by danotorrey** [comment]
@bernd I can't remember what we decided to do for AWS API permissions checking. Do you think it makes sense to add similar checks that are used in `InputsResource` (specifically the same `RestResource` INPUTS constants)? I was thinking it might make sense, since we're tying AWS directly into the inputs system.

**Comment by bernd** [comment]
@danotorrey Yes, let's use the input permissions in the AWS resources as well. :+1:

**Comment by danotorrey** [comment]
Closed VIA #113
