### ISSUE TITLE
Microsoft Teams notifications

### ISSUE THREAD

**Issue by edward-marrufo-graylog** [Graylog2/graylog-plugin-integrations#904]
## What?

As a Graylog user, I would like a Microsoft Teams notification built into Graylog that is not third party, similar to what you provide for Slack.

## Why?

Currently there is an existing plugin that works with Teams  on the marketplace however it would benefit us to have something officially supported from Graylog since if something breaks, we are on our own.

See HS-479801946

**Comment by bernd** [comment]
@edward-marrufo I moved this into the integrations repository.

**Comment by kingzacko1** [comment]
@bernd @edward-marrufo-graylog closed as of v4.3.2 with #1064
